CREATE SEQUENCE PUBLIC.GEEK_SEQ AS INTEGER START WITH 1000
CREATE MEMORY TABLE PUBLIC.GEEK(ID NUMERIC(128) NOT NULL PRIMARY KEY,GENRE VARCHAR(255) NOT NULL, NOM VARCHAR(255) NOT NULL,PRENOM VARCHAR(255) NOT NULL, AGE NUMERIC(3), MAIL VARCHAR(255) )

CREATE SEQUENCE PUBLIC.INTERET_SEQ AS INTEGER START WITH 1000
CREATE MEMORY TABLE PUBLIC.INTERET(ID NUMERIC(128) NOT NULL PRIMARY KEY,NOM VARCHAR(255) NOT NULL)

CREATE MEMORY TABLE PUBLIC.GEEK_INTERET(ID_GEEK NUMERIC(128), ID_INTERET NUMERIC(128), FOREIGN KEY(ID_GEEK) REFERENCES PUBLIC.GEEK(ID),FOREIGN KEY(ID_INTERET) REFERENCES PUBLIC.INTERET(ID))

INSERT INTO PUBLIC.GEEK VALUES (1,'HOMME','HALTER','Romain',22,'romainhalter@gmx.fr');
INSERT INTO PUBLIC.GEEK VALUES (2,'FEMME','CAMILLE','Elodie',21,'ecamille@gmail.com');
INSERT INTO PUBLIC.GEEK VALUES (3,'HOMME','NIZET','Jean-Baptiste',32,'jb@ninja-squad.com');
INSERT INTO PUBLIC.GEEK VALUES (4,'FEMME','BERGER','Sophie',27,'bsophie@gmail.com');

INSERT INTO PUBLIC.INTERET VALUES (1,'C');
INSERT INTO PUBLIC.INTERET VALUES (2,'Java');
INSERT INTO PUBLIC.INTERET VALUES (3,'JS');
INSERT INTO PUBLIC.INTERET VALUES (4,'HTML');
INSERT INTO PUBLIC.INTERET VALUES (5,'PYTHON');

INSERT INTO PUBLIC.GEEK_INTERET VALUES (1,1);
INSERT INTO PUBLIC.GEEK_INTERET VALUES (2,4);
INSERT INTO PUBLIC.GEEK_INTERET VALUES (2,3);
INSERT INTO PUBLIC.GEEK_INTERET VALUES (1,4);
INSERT INTO PUBLIC.GEEK_INTERET VALUES (3,2);
INSERT INTO PUBLIC.GEEK_INTERET VALUES (3,3);
INSERT INTO PUBLIC.GEEK_INTERET VALUES (4,1);
INSERT INTO PUBLIC.GEEK_INTERET VALUES (4,2);
INSERT INTO PUBLIC.GEEK_INTERET VALUES (4,3);
